# Generated by Django 2.2.1 on 2019-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_colaborador_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='empregados',
            field=models.ManyToManyField(to='clientes.Colaborador'),
        ),
    ]
