# Generated by Django 2.2.1 on 2019-06-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20190616_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.CPF'),
        ),
    ]
